const beaches=[
{name:'Централен плаж Бургас',lat:42.4926594892,lng:27.4822424349,flag:'green',score:92,waves:'0.3 m',water:'25.4°C',wind:'9 km/h',coordinateStatus:'official',coordinateSource:'Министерство на туризма',lifeguard:{status:'unknown',posts:[],note:'Точните постове още не са потвърдени.'}},
{name:'Хармани, Созопол',group:'Созопол',segment:'harmani',lat:42.4130713,lng:27.7015395,flag:'yellow',score:78,waves:'0.7 m',water:'25.1°C',wind:'18 km/h',coordinateStatus:'official',coordinateSource:'Министерство на туризма',lifeguard:{status:'unknown',posts:[],note:'Точните постове още не са потвърдени.'}},

{name:'Златни пясъци',lat:43.283909,lng:28.045143,flag:'green',score:88,waves:'0.4 m',water:'24.8°C',wind:'11 km/h',coordinateStatus:'verified',coordinateSource:'kilometri.bg / open geographic data',lifeguard:{status:'unknown',posts:[],note:'Точните постове още не са потвърдени.'}},
{name:'Кранево',lat:43.339966,lng:28.069176,flag:'green',score:86,waves:'0.4 m',water:'24.7°C',wind:'10 km/h',coordinateStatus:'verified',coordinateSource:'kilometri.bg',lifeguard:{status:'unknown',posts:[],note:'Точните постове още не са потвърдени.'}},
{name:'Албена',lat:43.371841,lng:28.087933,flag:'green',score:90,waves:'0.3 m',water:'24.6°C',wind:'9 km/h',coordinateStatus:'verified',coordinateSource:'kilometri.bg',lifeguard:{status:'unknown',posts:[],note:'Точните постове още не са потвърдени.'}},
{name:'Балчик Централен',lat:43.4032835408,lng:28.1690756824,flag:'yellow',score:75,waves:'0.6 m',water:'24.5°C',wind:'16 km/h',coordinateStatus:'official',coordinateSource:'Министерство на туризма',lifeguard:{status:'unknown',posts:[],note:'Точните постове още не са потвърдени.'}},
{name:'Каварна',lat:43.4131744437,lng:28.3571950798,flag:'yellow',score:73,waves:'0.7 m',water:'24.3°C',wind:'18 km/h',coordinateStatus:'official',coordinateSource:'Министерство на туризма',lifeguard:{status:'unknown',posts:[],note:'Плажната точка около Каварна още се уточнява.'}},
{name:'Варна Централен',lat:43.2023134,lng:27.9244974,flag:'green',score:87,waves:'0.4 m',water:'25.0°C',wind:'12 km/h',coordinateStatus:'official',coordinateSource:'Министерство на туризма',lifeguard:{status:'unknown',posts:[],note:'Централната плажна точка във Варна още се проверява.'}},
{name:'Поморие Централен',lat:42.5669475987,lng:27.6397632059,flag:'green',score:85,waves:'0.4 m',water:'25.2°C',wind:'13 km/h',coordinateStatus:'official',coordinateSource:'Министерство на туризма',lifeguard:{status:'unknown',posts:[],note:'Централната плажна точка в Поморие още се проверява.'}},
{name:'Несебър Южен плаж',lat:42.653866,lng:27.714540,flag:'yellow',score:77,waves:'0.6 m',water:'25.0°C',wind:'17 km/h',coordinateStatus:'verified',coordinateSource:'kilometri.bg',lifeguard:{status:'unknown',posts:[],note:'Точните постове още не са потвърдени.'}},
{name:'Приморско Северен',group:'Приморско',segment:'north',lat:42.2773557,lng:27.7549173,flag:'green',score:89,waves:'0.4 m',water:'25.3°C',wind:'11 km/h',coordinateStatus:'official',coordinateSource:'Министерство на туризма',lifeguard:{status:'unknown',posts:[],note:'Точните постове още не са потвърдени.'}},
{name:'Китен Атлиман',lat:42.24047,lng:27.76949,flag:'green',score:91,waves:'0.3 m',water:'25.4°C',wind:'9 km/h',coordinateStatus:'verified',coordinateSource:'plajovete.com 2026 / OpenStreetMap-derived reference',lifeguard:{status:'unknown',posts:[],note:'Точните постове още не са потвърдени.'}},
{name:'Лозенец Централен',lat:42.2131996,lng:27.8041289,flag:'yellow',score:79,waves:'0.6 m',water:'25.2°C',wind:'16 km/h',coordinateStatus:'official',coordinateSource:'Министерство на туризма',lifeguard:{status:'unknown',posts:[],note:'Точните постове още не са потвърдени.'}},
{name:'Царево Централен',lat:42.1733155,lng:27.8506656,flag:'green',score:84,waves:'0.4 m',water:'25.1°C',wind:'12 km/h',coordinateStatus:'official',coordinateSource:'Министерство на туризма',lifeguard:{status:'unknown',posts:[],note:'Точните постове още не са потвърдени.'}},
{name:'Ахтопол Централен',lat:42.0976,lng:27.9430,flag:'yellow',score:76,waves:'0.7 m',water:'25.0°C',wind:'18 km/h',coordinateStatus:'needs_review',coordinateSource:'legacy prototype',lifeguard:{status:'unknown',posts:[],note:'Точната плажна точка в Ахтопол още се проверява.'}},
{name:'Синеморец Бутамята',group:'Синеморец',segment:'butamyata',lat:42.054596,lng:27.986870,flag:'green',score:93,waves:'0.4 m',water:'24.9°C',wind:'10 km/h',coordinateStatus:'verified',coordinateSource:'kilometri.bg / current beach references',lifeguard:{status:'unknown',posts:[],note:'Точните постове още не са потвърдени.'}}
,
{name:'Крапец',lat:43.64334,lng:28.57381,flag:'green',score:82,waves:'0.3 m',water:'23.8°C',wind:'10 km/h',coordinateStatus:'verified',coordinateSource:'plajovete.com 2026',lifeguard:{status:'unknown',posts:[],note:'Спасителната информация още се проверява.'}},

{name:'Крайморие',lat:42.44576,lng:27.49168,flag:'green',score:84,waves:'0.3 m',water:'25.4°C',wind:'10 km/h',coordinateStatus:'verified',coordinateSource:'plajovete.com 2026',lifeguard:{status:'unknown',posts:[],note:'Спасителната информация още се проверява.'}},
{name:'Росенец',lat:42.44543,lng:27.57321,flag:'green',score:81,waves:'0.3 m',water:'25.4°C',wind:'10 km/h',coordinateStatus:'verified',coordinateSource:'plajovete.com 2026',lifeguard:{status:'unknown',posts:[],note:'Спасителната информация още се проверява.'}},
{name:'Градина',lat:42.41934,lng:27.64684,flag:'green',score:88,waves:'0.4 m',water:'25.4°C',wind:'11 km/h',coordinateStatus:'verified',coordinateSource:'plajovete.com 2026',lifeguard:{status:'guarded',posts:[],note:'Източникът посочва охраняем плаж; точните GPS позиции на постовете още се проверяват.'}},
{name:'Созопол Централен',group:'Созопол',segment:'central',lat:42.4198682,lng:27.6950962,flag:'green',score:87,waves:'0.4 m',water:'24.9°C',wind:'10 km/h',coordinateStatus:'official',coordinateSource:'Министерство на туризма',lifeguard:{status:'unknown',posts:[],note:'Точните постове още се проверяват.'}},
{name:'Каваците',lat:42.39600,lng:27.70660,flag:'green',score:90,waves:'0.4 m',water:'25.1°C',wind:'10 km/h',coordinateStatus:'verified',coordinateSource:'plajovete.com 2026',lifeguard:{status:'guarded',posts:[],note:'Източникът посочва охраняем плаж; точните GPS позиции на постовете още се проверяват.'}},
{name:'Смокиня',lat:42.38797,lng:27.70660,flag:'green',score:89,waves:'0.4 m',water:'25.1°C',wind:'10 km/h',coordinateStatus:'verified',coordinateSource:'plajovete.com 2026',lifeguard:{status:'guarded',posts:[],note:'Източникът посочва охраняем плаж; точните GPS позиции на постовете още се проверяват.'}},
{name:'ММЦ',group:'Приморско',segment:'mmc',lat:42.25185,lng:27.75164,flag:'green',score:86,waves:'0.5 m',water:'25.1°C',wind:'10 km/h',coordinateStatus:'verified',coordinateSource:'plajovete.com 2026',lifeguard:{status:'guarded',posts:[],note:'Източникът посочва охраняем плаж; точните GPS позиции на постовете още се проверяват.'}},
{name:'Караагач',lat:42.22758,lng:27.77670,flag:'green',score:84,waves:'0.5 m',water:'25.1°C',wind:'10 km/h',coordinateStatus:'verified',coordinateSource:'plajovete.com 2026',lifeguard:{status:'guarded',posts:[],note:'Източникът посочва охраняем плаж; точните GPS позиции на постовете още се проверяват.'}},
{name:'Гардения',lat:42.22337,lng:27.78264,flag:'green',score:83,waves:'0.5 m',water:'25.1°C',wind:'10 km/h',coordinateStatus:'verified',coordinateSource:'plajovete.com 2026',lifeguard:{status:'unknown',posts:[],note:'Спасителната информация още се проверява.'}},
{name:'Корал',lat:42.2162102,lng:27.7914404,flag:'yellow',score:74,waves:'0.5 m',water:'25.1°C',wind:'12 km/h',coordinateStatus:'official',coordinateSource:'Министерство на туризма',lifeguard:{status:'unguarded',posts:[],note:'Част от плажа е неохраняема; официалният статут се пази отделно в каталога.'}},
{name:'Оазис',lat:42.20018,lng:27.81924,flag:'green',score:88,waves:'0.5 m',water:'24.9°C',wind:'11 km/h',coordinateStatus:'verified',coordinateSource:'plajovete.com 2026',lifeguard:{status:'guarded',posts:[],note:'Източникът посочва охраняем плаж; точните GPS позиции на постовете още се проверяват.'}},
{name:'Варвара',group:'Варвара',segment:'central',lat:42.12773,lng:27.90747,flag:'green',score:82,waves:'0.5 m',water:'24.9°C',wind:'10 km/h',coordinateStatus:'verified',coordinateSource:'plajovete.com 2026',lifeguard:{status:'unknown',posts:[],note:'Спасителната информация още се проверява.'}},
{name:'Варвара - север',group:'Варвара',segment:'north',lat:42.12871,lng:27.90422,flag:'yellow',score:76,waves:'0.5 m',water:'24.9°C',wind:'10 km/h',coordinateStatus:'verified',coordinateSource:'plajovete.com 2026',lifeguard:{status:'unguarded',posts:[],note:'Див/неохраняем участък според текущия каталог.'}},
{name:'Делфин',lat:42.10679,lng:27.91939,flag:'green',score:85,waves:'0.5 m',water:'24.8°C',wind:'10 km/h',coordinateStatus:'verified',coordinateSource:'plajovete.com 2026',lifeguard:{status:'guarded',posts:[],note:'Източникът посочва охраняем плаж; точните GPS позиции на постовете още се проверяват.'}},
{name:'Силистар',lat:42.02179,lng:28.00980,flag:'green',score:92,waves:'0.7 m',water:'24.7°C',wind:'9 km/h',coordinateStatus:'verified',coordinateSource:'plajovete.com 2026',lifeguard:{status:'unknown',posts:[],note:'Точните постове още се проверяват.'}},
{name:'Дуранкулак - север 1',group:'Дуранкулак',segment:'north-1',lat:43.719761,lng:28.572729,flag:'green',score:78,waves:'0.4 m',water:'23.6°C',wind:'12 km/h',coordinateStatus:'verified',coordinateSource:'kilometri.bg',lifeguard:{status:'unguarded',posts:[],note:'Официално неохраняем участък.'}},
{name:'Дуранкулак - север 2',group:'Дуранкулак',segment:'north-2',lat:43.696209,lng:28.565935,flag:'green',score:79,waves:'0.4 m',water:'23.6°C',wind:'12 km/h',coordinateStatus:'verified',coordinateSource:'kilometri.bg',lifeguard:{status:'unguarded',posts:[],note:'Официално неохраняем участък.'}},
{name:'Езерец',lat:43.590683,lng:28.571623,flag:'green',score:82,waves:'0.4 m',water:'23.7°C',wind:'11 km/h',coordinateStatus:'verified',coordinateSource:'kilometri.bg',lifeguard:{status:'unknown',posts:[],note:'Спасителната информация още се проверява.'}},
{name:'Шабла',lat:43.5645865978,lng:28.5898445471,flag:'green',score:81,waves:'0.4 m',water:'23.8°C',wind:'11 km/h',coordinateStatus:'official',coordinateSource:'Министерство на туризма',lifeguard:{status:'unguarded',posts:[],note:'Официално неохраняем плаж през сезон 2026.'}},
{name:'Болата',lat:43.382915,lng:28.470106,flag:'green',score:90,waves:'0.2 m',water:'24.0°C',wind:'9 km/h',coordinateStatus:'verified',coordinateSource:'kilometri.bg',lifeguard:{status:'unguarded',posts:[],note:'Официално неохраняем плаж през сезон 2026.'}},
{name:'Русалка',lat:43.416138,lng:28.509438,flag:'green',score:86,waves:'0.3 m',water:'24.0°C',wind:'10 km/h',coordinateStatus:'verified',coordinateSource:'kilometri.bg',lifeguard:{status:'unguarded',posts:[],note:'Комплекс от плажове; официално е в списъка на неохраняемите за 2026.'}},
{name:'Херос',lat:43.408936,lng:28.256683,flag:'green',score:83,waves:'0.4 m',water:'24.2°C',wind:'11 km/h',coordinateStatus:'verified',coordinateSource:'kilometri.bg',lifeguard:{status:'unknown',posts:[],note:'Спасителната информация още се проверява.'}},
{name:'Кибела',lat:43.412529,lng:28.271912,flag:'green',score:84,waves:'0.4 m',water:'24.2°C',wind:'11 km/h',coordinateStatus:'verified',coordinateSource:'kilometri.bg',lifeguard:{status:'unknown',posts:[],note:'Спасителната информация още се проверява.'}},
{name:'Слънчев ден',lat:43.243710,lng:28.019241,flag:'green',score:88,waves:'0.3 m',water:'24.7°C',wind:'10 km/h',coordinateStatus:'verified',coordinateSource:'kilometri.bg',lifeguard:{status:'unknown',posts:[],note:'Точните постове още се проверяват.'}},
{name:'Сахара',lat:43.236504,lng:28.015684,flag:'green',score:87,waves:'0.3 m',water:'24.8°C',wind:'10 km/h',coordinateStatus:'verified',coordinateSource:'kilometri.bg',lifeguard:{status:'unknown',posts:[],note:'Точните постове още се проверяват.'}},
{name:'Сириус',lat:43.233105,lng:28.014881,flag:'green',score:86,waves:'0.3 m',water:'24.8°C',wind:'10 km/h',coordinateStatus:'verified',coordinateSource:'kilometri.bg',lifeguard:{status:'unknown',posts:[],note:'Точните постове още се проверяват.'}},
{name:'Раджана',lat:43.231026,lng:28.014795,flag:'green',score:85,waves:'0.3 m',water:'24.8°C',wind:'10 km/h',coordinateStatus:'verified',coordinateSource:'kilometri.bg',lifeguard:{status:'unknown',posts:[],note:'Точните постове още се проверяват.'}},
{name:'The Bay',lat:43.228008,lng:28.013281,flag:'green',score:85,waves:'0.3 m',water:'24.8°C',wind:'10 km/h',coordinateStatus:'verified',coordinateSource:'kilometri.bg',lifeguard:{status:'unknown',posts:[],note:'Точните постове още се проверяват.'}},
{name:'Траката',lat:43.219379637723,lng:27.981303510713,flag:'green',score:80,waves:'0.3 m',water:'24.9°C',wind:'10 km/h',coordinateStatus:'official',coordinateSource:'Министерство на туризма',lifeguard:{status:'unknown',posts:[],note:'Спасителната информация още се проверява.'}},
{name:'Офицерски плаж Варна',lat:43.209076,lng:27.938484,flag:'green',score:83,waves:'0.3 m',water:'25.0°C',wind:'10 km/h',coordinateStatus:'verified',coordinateSource:'kilometri.bg',lifeguard:{status:'unguarded',posts:[],note:'В официалния списък на неохраняемите плажове за 2026.'}},
{name:'Рапонги',lat:43.209499,lng:27.940666,flag:'green',score:84,waves:'0.3 m',water:'25.0°C',wind:'10 km/h',coordinateStatus:'verified',coordinateSource:'kilometri.bg',lifeguard:{status:'unknown',posts:[],note:'Спасителната информация още се проверява.'}},
{name:'Фичоза',lat:43.143154,lng:27.939997,flag:'green',score:79,waves:'0.4 m',water:'24.8°C',wind:'11 km/h',coordinateStatus:'verified',coordinateSource:'kilometri.bg',lifeguard:{status:'unguarded',posts:[],note:'Официално неохраняем плаж през сезон 2026.'}},
{name:'Паша дере',lat:43.121101,lng:27.928703,flag:'green',score:82,waves:'0.4 m',water:'24.7°C',wind:'11 km/h',coordinateStatus:'verified',coordinateSource:'kilometri.bg',lifeguard:{status:'unguarded',posts:[],note:'Официално неохраняем плаж през сезон 2026.'}},

{name:'Камчийски пясъци',lat:42.982269,lng:27.891418,flag:'green',score:87,waves:'0.5 m',water:'24.5°C',wind:'12 km/h',coordinateStatus:'verified',coordinateSource:'kilometri.bg',lifeguard:{status:'unknown',posts:[],note:'Спасителната информация още се проверява.'}},
{name:'Кара дере',lat:42.9177739,lng:27.8963164,flag:'green',score:91,waves:'0.5 m',water:'24.5°C',wind:'11 km/h',coordinateStatus:'official',coordinateSource:'Министерство на туризма',lifeguard:{status:'unknown',posts:[],note:'Див плаж; статутът на охраняване още се проверява.'}},
{name:'Бяла',lat:42.864632,lng:27.899067,flag:'green',score:86,waves:'0.4 m',water:'24.6°C',wind:'11 km/h',coordinateStatus:'verified',coordinateSource:'kilometri.bg',lifeguard:{status:'unknown',posts:[],note:'Спасителната информация още се проверява.'}},
{name:'Обзор',lat:42.821953,lng:27.884237,flag:'green',score:88,waves:'0.4 m',water:'24.7°C',wind:'11 km/h',coordinateStatus:'verified',coordinateSource:'kilometri.bg',lifeguard:{status:'unknown',posts:[],note:'Спасителната информация още се проверява.'}},
{name:'Иракли',lat:42.7409219,lng:27.8912491,flag:'yellow',score:81,waves:'0.6 m',water:'24.8°C',wind:'14 km/h',coordinateStatus:'official',coordinateSource:'Министерство на туризма',lifeguard:{status:'unguarded',posts:[],note:'Официално неохраняем плаж с частично сезонно водноспасително обезпечаване.'}},
{name:'Свети Влас Централен',lat:42.708328,lng:27.759096,flag:'green',score:87,waves:'0.3 m',water:'25.0°C',wind:'10 km/h',coordinateStatus:'verified',coordinateSource:'kilometri.bg',lifeguard:{status:'guarded',posts:[],note:'Охраняем плаж; точните GPS позиции на постовете още се проверяват.'}},
{name:'Какао',lat:42.673649,lng:27.711655,flag:'green',score:86,waves:'0.4 m',water:'25.0°C',wind:'11 km/h',coordinateStatus:'verified',coordinateSource:'kilometri.bg',lifeguard:{status:'unknown',posts:[],note:'Спасителната информация още се проверява.'}},
{name:'Черноморец Централен',lat:42.448601,lng:27.635620,flag:'green',score:86,waves:'0.4 m',water:'25.2°C',wind:'10 km/h',coordinateStatus:'verified',coordinateSource:'kilometri.bg',lifeguard:{status:'unknown',posts:[],note:'Спасителната информация още се проверява.'}},
{name:'Нестинарка',lat:42.157848,lng:27.866709,flag:'green',score:89,waves:'0.4 m',water:'25.0°C',wind:'10 km/h',coordinateStatus:'verified',coordinateSource:'kilometri.bg',lifeguard:{status:'unknown',posts:[],note:'Спасителната информация още се проверява.'}},
{name:'Василико',lat:42.163473877851,lng:27.861809173382,flag:'green',score:85,waves:'0.4 m',water:'25.0°C',wind:'10 km/h',coordinateStatus:'official',coordinateSource:'Министерство на туризма',lifeguard:{status:'unknown',posts:[],note:'Спасителната информация още се проверява.'}},
{name:'Арапя',lat:42.189041,lng:27.836378,flag:'green',score:88,waves:'0.4 m',water:'25.0°C',wind:'10 km/h',coordinateStatus:'verified',coordinateSource:'kilometri.bg',lifeguard:{status:'unknown',posts:[],note:'Спасителната информация още се проверява.'}},
{name:'Приморско Южен',group:'Приморско',segment:'south',lat:42.2619710908,lng:27.7519254473,flag:'green',score:88,waves:'0.4 m',water:'25.2°C',wind:'10 km/h',coordinateStatus:'official',coordinateSource:'Министерство на туризма',lifeguard:{status:'unknown',posts:[],note:'Спасителната информация още се проверява.'}},
{name:'Перла',group:'Приморско',segment:'perla',lat:42.289062,lng:27.757217,flag:'green',score:90,waves:'0.4 m',water:'25.2°C',wind:'10 km/h',coordinateStatus:'verified',coordinateSource:'kilometri.bg',lifeguard:{status:'unknown',posts:[],note:'Спасителната информация още се проверява.'}},
{name:'Липите',lat:42.047085,lng:27.991184,flag:'green',score:92,waves:'0.5 m',water:'24.8°C',wind:'9 km/h',coordinateStatus:'verified',coordinateSource:'kilometri.bg',lifeguard:{status:'unguarded',posts:[],note:'Официално неохраняем плаж през сезон 2026.'}},
{name:'Листи',lat:42.034897,lng:28.003380,flag:'green',score:91,waves:'0.5 m',water:'24.8°C',wind:'9 km/h',coordinateStatus:'verified',coordinateSource:'kilometri.bg',lifeguard:{status:'unguarded',posts:[],note:'Официално неохраняем плаж през сезон 2026.'}},
{name:'Синеморец Северен',group:'Синеморец',segment:'north',lat:42.067257,lng:27.972078,flag:'green',score:92,waves:'0.5 m',water:'24.8°C',wind:'9 km/h',coordinateStatus:'verified',coordinateSource:'kilometri.bg',lifeguard:{status:'unknown',posts:[],note:'Спасителната информация още се проверява.'}},
{name:'Кастрич',group:'Резово/Кастрич',segment:'kastrich',lat:42.006279,lng:28.018831,flag:'green',score:89,waves:'0.5 m',water:'24.6°C',wind:'9 km/h',coordinateStatus:'verified',coordinateSource:'kilometri.bg',lifeguard:{status:'unknown',posts:[],note:'Спасителната информация още се проверява.'}},
{name:'Малък Кастрич',group:'Резово/Кастрич',segment:'small-kastrich',lat:42.010914,lng:28.017078,flag:'green',score:89,waves:'0.5 m',water:'24.6°C',wind:'9 km/h',coordinateStatus:'verified',coordinateSource:'kilometri.bg',lifeguard:{status:'unknown',posts:[],note:'Спасителната информация още се проверява.'}}
,
{name:'Слънчев бряг - север',group:'Слънчев бряг',segment:'north',lat:42.7013792,lng:27.7199961,flag:'green',score:86,waves:'0.4 m',water:'25.0°C',wind:'11 km/h',coordinateStatus:'official',coordinateSource:'Министерство на туризма',lifeguard:{status:'guarded',posts:[],note:'Официален плажен участък. Флагът е тестов, докато не свържем live данни.'}},
{name:'Слънчев бряг - централен',group:'Слънчев бряг',segment:'central',lat:42.6876691,lng:27.7131129,flag:'green',score:87,waves:'0.4 m',water:'25.0°C',wind:'11 km/h',coordinateStatus:'official',coordinateSource:'Министерство на туризма',lifeguard:{status:'guarded',posts:[],note:'Официален плажен участък. Флагът е тестов, докато не свържем live данни.'}},
{name:'Слънчев бряг - юг',group:'Слънчев бряг',segment:'south',lat:42.6712988119,lng:27.7122180101,flag:'green',score:85,waves:'0.4 m',water:'25.0°C',wind:'11 km/h',coordinateStatus:'official',coordinateSource:'Министерство на туризма',lifeguard:{status:'guarded',posts:[],note:'Официален плажен участък. Флагът е тестов, докато не свържем live данни.'}},

{name:'Камчия - север 1/2/4/5',group:'Камчия',segment:'north',lat:43.0342640563,lng:27.8884093385,flag:'yellow',score:76,waves:'0.4 m',water:'24.3°C',wind:'11 km/h',coordinateStatus:'official',coordinateSource:'Министерство на туризма',lifeguard:{status:'unguarded',posts:[],note:'Официално неохраняем плажен участък.'}},
{name:'Камчия - юг',group:'Камчия',segment:'south',lat:43.0255215787,lng:27.8884469046,flag:'yellow',score:75,waves:'0.4 m',water:'24.3°C',wind:'11 km/h',coordinateStatus:'official',coordinateSource:'Министерство на туризма',lifeguard:{status:'unguarded',posts:[],note:'Официално неохраняем плажен участък.'}},

{name:'Шкорпиловци - север',group:'Шкорпиловци',segment:'north',lat:43.0022725422,lng:27.8887687623,flag:'yellow',score:77,waves:'0.5 m',water:'24.5°C',wind:'12 km/h',coordinateStatus:'official',coordinateSource:'Министерство на туризма',lifeguard:{status:'unguarded',posts:[],note:'Официално неохраняем плажен участък.'}},
{name:'Шкорпиловци - юг',group:'Шкорпиловци',segment:'south',lat:42.9470629102,lng:27.9010777187,flag:'green',score:84,waves:'0.5 m',water:'24.5°C',wind:'12 km/h',coordinateStatus:'official',coordinateSource:'Министерство на туризма',lifeguard:{status:'guarded',posts:[],note:'Официален плажен участък под наем; точните спасителни постове още се проверяват.'}}
,
{name:'Нов плаж Балчик',group:'Балчик',segment:'new',lat:43.4053491431,lng:28.1578640558,flag:'green',score:84,waves:'0.4 m',water:'25.0°C',wind:'11 km/h',coordinateStatus:'official',coordinateSource:'Министерство на туризма',officialCategory:'наем',lifeguard:{status:'guarded',posts:[],note:'Официален плажен участък; точните спасителни постове още се проверяват.'}},
{name:'Балчик - двореца',group:'Балчик',segment:'palace',lat:43.403041899,lng:28.1461910753,flag:'green',score:84,waves:'0.4 m',water:'25.0°C',wind:'11 km/h',coordinateStatus:'official',coordinateSource:'Министерство на туризма',officialCategory:'наем',lifeguard:{status:'guarded',posts:[],note:'Официален плажен участък; точните спасителни постове още се проверяват.'}},
{name:'Камчия - север 3',group:'Камчия',segment:'north3',lat:43.02902129485,lng:27.888287550076,flag:'green',score:84,waves:'0.4 m',water:'25.0°C',wind:'11 km/h',coordinateStatus:'official',coordinateSource:'Министерство на туризма',officialCategory:'наем',lifeguard:{status:'guarded',posts:[],note:'Официален плажен участък; точните спасителни постове още се проверяват.'}},
{name:'Поморие - буната',group:'Поморие',segment:'bunata',lat:42.5539663336,lng:27.6495830652,flag:'yellow',score:76,waves:'0.4 m',water:'25.0°C',wind:'11 km/h',coordinateStatus:'official',coordinateSource:'Министерство на туризма',officialCategory:'неохраняем',lifeguard:{status:'unguarded',posts:[],note:'Официално неохраняем плажен участък.'}},
{name:'Поморие - изток',group:'Поморие',segment:'east',lat:42.5573707121,lng:27.6478419838,flag:'green',score:84,waves:'0.4 m',water:'25.0°C',wind:'11 km/h',coordinateStatus:'official',coordinateSource:'Министерство на туризма',officialCategory:'концесия',lifeguard:{status:'guarded',posts:[],note:'Официален плажен участък; точните спасителни постове още се проверяват.'}},
{name:'Поморие - юг',group:'Поморие',segment:'south',lat:42.5634495584,lng:27.6060132769,flag:'green',score:84,waves:'0.4 m',water:'25.0°C',wind:'11 km/h',coordinateStatus:'official',coordinateSource:'Министерство на туризма',officialCategory:'концесия',lifeguard:{status:'guarded',posts:[],note:'Официален плажен участък; точните спасителни постове още се проверяват.'}},
{name:'Поморие - Почивни станции',group:'Поморие',segment:'stations',lat:42.569040019565,lng:27.637247294557,flag:'green',score:84,waves:'0.4 m',water:'25.0°C',wind:'11 km/h',coordinateStatus:'official',coordinateSource:'Министерство на туризма',officialCategory:'наем',lifeguard:{status:'guarded',posts:[],note:'Официален плажен участък; точните спасителни постове още се проверяват.'}},
{name:'Созопол - запад - част 1, 2 и 3',group:'Созопол',segment:'west',lat:42.414062269769,lng:27.685940131377,flag:'green',score:84,waves:'0.4 m',water:'25.0°C',wind:'11 km/h',coordinateStatus:'official',coordinateSource:'Министерство на туризма',officialCategory:'наем',lifeguard:{status:'guarded',posts:[],note:'Официален плажен участък; точните спасителни постове още се проверяват.'}},
{name:'Созопол - Буджака',group:'Созопол',segment:'budzhaka',lat:42.409113,lng:27.7052737,flag:'green',score:84,waves:'0.4 m',water:'25.0°C',wind:'11 km/h',coordinateStatus:'official',coordinateSource:'Министерство на туризма',officialCategory:'концесия',lifeguard:{status:'guarded',posts:[],note:'Официален плажен участък; точните спасителни постове още се проверяват.'}},
{name:'Къмпинг Ахелой - част 3',group:'Ахелой',segment:'camp3',lat:42.629514585415,lng:27.637731404531,flag:'green',score:84,waves:'0.4 m',water:'25.0°C',wind:'11 km/h',coordinateStatus:'official',coordinateSource:'Министерство на туризма',officialCategory:'наем',lifeguard:{status:'guarded',posts:[],note:'Официален плажен участък; точните спасителни постове още се проверяват.'}},
{name:'Бургас - север',group:'Бургас',segment:'north',lat:42.5041452933,lng:27.4838732108,flag:'green',score:84,waves:'0.4 m',water:'25.0°C',wind:'11 km/h',coordinateStatus:'official',coordinateSource:'Министерство на туризма',officialCategory:'концесия',lifeguard:{status:'guarded',posts:[],note:'Официален плажен участък; точните спасителни постове още се проверяват.'}},
{name:'Приморско - централен',group:'Приморско',segment:'central',lat:42.2700587066,lng:27.7586064797,flag:'green',score:84,waves:'0.4 m',water:'25.0°C',wind:'11 km/h',coordinateStatus:'official',coordinateSource:'Министерство на туризма',officialCategory:'концесия',lifeguard:{status:'guarded',posts:[],note:'Официален плажен участък; точните спасителни постове още се проверяват.'}},
{name:'Малък плаж - Лозенец',group:'Лозенец',segment:'small',lat:42.2087892396,lng:27.8106443593,flag:'green',score:84,waves:'0.4 m',water:'25.0°C',wind:'11 km/h',coordinateStatus:'official',coordinateSource:'Министерство на туризма',officialCategory:'концесия',lifeguard:{status:'guarded',posts:[],note:'Официален плажен участък; точните спасителни постове още се проверяват.'}},
{name:'Лозенец - юг',group:'Лозенец',segment:'south',lat:42.2029693613,lng:27.8181408269,flag:'yellow',score:76,waves:'0.4 m',water:'25.0°C',wind:'11 km/h',coordinateStatus:'official',coordinateSource:'Министерство на туризма',officialCategory:'неохраняем',lifeguard:{status:'unguarded',posts:[],note:'Официално неохраняем плажен участък.'}},
{name:'Ахтопол - фара',group:'Ахтопол',segment:'lighthouse',lat:42.1013405675,lng:27.9475037675,flag:'yellow',score:76,waves:'0.4 m',water:'25.0°C',wind:'11 km/h',coordinateStatus:'official',coordinateSource:'Министерство на туризма',officialCategory:'неохраняем',lifeguard:{status:'unguarded',posts:[],note:'Официално неохраняем плажен участък.'}},
{name:'Ахтопол - север - западна зона',group:'Ахтопол',segment:'north-west',lat:42.102097548879,lng:27.926928871219,flag:'yellow',score:76,waves:'0.4 m',water:'25.0°C',wind:'11 km/h',coordinateStatus:'official',coordinateSource:'Министерство на туризма',officialCategory:'неохраняем',lifeguard:{status:'unguarded',posts:[],note:'Официално неохраняем плажен участък.'}},
{name:'Ахтопол - север - източна зона',group:'Ахтопол',segment:'north-east',lat:42.1035296313,lng:27.9361526587,flag:'green',score:84,waves:'0.4 m',water:'25.0°C',wind:'11 km/h',coordinateStatus:'official',coordinateSource:'Министерство на туризма',officialCategory:'концесия',lifeguard:{status:'guarded',posts:[],note:'Официален плажен участък; точните спасителни постове още се проверяват.'}},
{name:'Царево - север 1',group:'Царево',segment:'north1',lat:42.1650663646,lng:27.8619174596,flag:'yellow',score:76,waves:'0.4 m',water:'25.0°C',wind:'11 km/h',coordinateStatus:'official',coordinateSource:'Министерство на туризма',officialCategory:'неохраняем',lifeguard:{status:'unguarded',posts:[],note:'Официално неохраняем плажен участък.'}},
{name:'Царево - север 2',group:'Царево',segment:'north2',lat:42.1648357456,lng:27.8620676633,flag:'yellow',score:76,waves:'0.4 m',water:'25.0°C',wind:'11 km/h',coordinateStatus:'official',coordinateSource:'Министерство на туризма',officialCategory:'неохраняем',lifeguard:{status:'unguarded',posts:[],note:'Официално неохраняем плажен участък.'}},
{name:'Царево - север 3',group:'Царево',segment:'north3',lat:42.16468465,lng:27.8630869028,flag:'yellow',score:76,waves:'0.4 m',water:'25.0°C',wind:'11 km/h',coordinateStatus:'official',coordinateSource:'Министерство на туризма',officialCategory:'неохраняем',lifeguard:{status:'unguarded',posts:[],note:'Официално неохраняем плажен участък.'}},
{name:'Царево - Попски',group:'Царево',segment:'popski',lat:42.164958980392,lng:27.861780368388,flag:'green',score:84,waves:'0.4 m',water:'25.0°C',wind:'11 km/h',coordinateStatus:'official',coordinateSource:'Министерство на туризма',officialCategory:'наем',lifeguard:{status:'guarded',posts:[],note:'Официален плажен участък; точните спасителни постове още се проверяват.'}}];

const officialUnguarded2026=[
{region:'Добрич',municipality:'Шабла',name:'Дуранкулак - север 1'},
{region:'Добрич',municipality:'Шабла',name:'Дуранкулак - север 2'},
{region:'Добрич',municipality:'Шабла',name:'Космос'},
{region:'Добрич',municipality:'Шабла',name:'Дуранкулак - езеро'},
{region:'Добрич',municipality:'Шабла',name:'Крапец-север - част'},
{region:'Добрич',municipality:'Шабла',name:'Крапец-централен'},
{region:'Добрич',municipality:'Шабла',name:'Крапец - юг'},
{region:'Добрич',municipality:'Шабла',name:'Шабла'},
{region:'Добрич',municipality:'Шабла',name:'Добруджа - север 1 и Добруджа - север 2'},
{region:'Добрич',municipality:'Шабла',name:'Добруджа - юг - част'},
{region:'Добрич',municipality:'Каварна',name:'Русалка (комплекс от плажове)'},
{region:'Добрич',municipality:'Каварна',name:'Тауклиман'},
{region:'Добрич',municipality:'Каварна',name:'Болата'},
{region:'Добрич',municipality:'Балчик',name:'Тузлата'},
{region:'Добрич',municipality:'Балчик',name:'Сребристият бряг'},
{region:'Добрич',municipality:'Балчик',name:'Робинзон 2'},
{region:'Добрич',municipality:'Балчик',name:'Фиш - фиш - нов'},

{region:'Варна',municipality:'Варна',name:'Чайка - централен 2'},
{region:'Варна',municipality:'Варна',name:'Чайка - централен 1'},
{region:'Варна',municipality:'Варна',name:'Чайка - юг'},
{region:'Варна',municipality:'Варна',name:'Минерален басейн - юг'},
{region:'Варна',municipality:'Варна',name:'Евксиноград 1'},
{region:'Варна',municipality:'Варна',name:'Евксиноград 2'},
{region:'Варна',municipality:'Варна',name:'Евксиноград 3'},
{region:'Варна',municipality:'Варна',name:'Офицерски'},
{region:'Варна',municipality:'Варна',name:'Галата - север'},
{region:'Варна',municipality:'Варна',name:'Галата - изток'},
{region:'Варна',municipality:'Варна',name:'Фичоза - север'},
{region:'Варна',municipality:'Варна',name:'Фичоза'},
{region:'Варна',municipality:'Варна',name:'Фичоза - юг'},
{region:'Варна',municipality:'Варна',name:'Хижа Черноморец - север'},
{region:'Варна',municipality:'Варна',name:'Паша дере'},
{region:'Варна',municipality:'Аврен',name:'Романтика'},
{region:'Варна',municipality:'Аврен',name:'Камчия - север 1, 2, 4 и 5'},
{region:'Варна',municipality:'Долни Чифлик',name:'Камчия-юг'},
{region:'Варна',municipality:'Долни Чифлик',name:'Изгрев - Хоризонт'},
{region:'Варна',municipality:'Долни Чифлик',name:'Шкорпиловци - север'},
{region:'Варна',municipality:'Бяла',name:'Бяла - север'},
{region:'Варна',municipality:'Бяла',name:'Бяла - централен I'},
{region:'Варна',municipality:'Бяла',name:'Бяла - централен III'},
{region:'Варна',municipality:'Бяла',name:'Бяла - централен IV'},
{region:'Варна',municipality:'Бяла',name:'Бяла - Чайка, в т.ч. Бяла - Чайка 1'},

{region:'Бургас',municipality:'Несебър',name:'Смриките'},
{region:'Бургас',municipality:'Несебър',name:'Емона - юг'},
{region:'Бургас',municipality:'Несебър',name:'Емона - Бунарджика'},
{region:'Бургас',municipality:'Несебър',name:'Елените - изток 1 и 2'},
{region:'Бургас',municipality:'Несебър',name:'Елените 1 и 2'},
{region:'Бургас',municipality:'Несебър',name:'Козлука'},
{region:'Бургас',municipality:'Несебър',name:'Робинзон-запад 2'},
{region:'Бургас',municipality:'Несебър',name:'Несебър- изток'},
{region:'Бургас',municipality:'Поморие',name:'Ахелой -север'},
{region:'Бургас',municipality:'Поморие',name:'Къмпинг Ахелой - без част 3'},
{region:'Бургас',municipality:'Поморие',name:'Поморийска коса'},
{region:'Бургас',municipality:'Поморие',name:'Поморие Буната'},
{region:'Бургас',municipality:'Поморие',name:'Къмпинг Европа'},
{region:'Бургас',municipality:'Поморие',name:'Лахана 1'},
{region:'Бургас',municipality:'Бургас',name:'Сарафово - север'},
{region:'Бургас',municipality:'Бургас',name:'Атанасовска коса - част 2'},
{region:'Бургас',municipality:'Бургас',name:'Крайморие - север 1'},
{region:'Бургас',municipality:'Бургас',name:'Крайморие - север 2'},
{region:'Бургас',municipality:'Бургас',name:'Крайморие - север 3'},
{region:'Бургас',municipality:'Бургас',name:'Крайморие - юг 1 и 2'},
{region:'Бургас',municipality:'Бургас',name:'Росенец'},
{region:'Бургас',municipality:'Бургас',name:'Отманли'},
{region:'Бургас',municipality:'Бургас',name:'Росенец - запад'},
{region:'Бургас',municipality:'Бургас',name:'Росенец - централен'},
{region:'Бургас',municipality:'Бургас',name:'Росенец - изток'},
{region:'Бургас',municipality:'Созопол',name:'Вромос'},
{region:'Бургас',municipality:'Созопол',name:'Алепу'},
{region:'Бургас',municipality:'Приморско',name:'Аркутино лилии'},
{region:'Бургас',municipality:'Приморско',name:'Ропотамо'},
{region:'Бургас',municipality:'Царево',name:'Лозенец-юг'},
{region:'Бургас',municipality:'Царево',name:'Малък оазис 1, 2, 3 и 4'},
{region:'Бургас',municipality:'Царево',name:'Малък оазис зона 1,2,4 - централен-изток'},
{region:'Бургас',municipality:'Царево',name:'Царево - север 1, 2 и 3'},
{region:'Бургас',municipality:'Царево',name:'Попски плаж - север 1, 2, 3, 4 и 5'},
{region:'Бургас',municipality:'Царево',name:'Царево - централен'},
{region:'Бургас',municipality:'Царево',name:'Царево - Василико'},
{region:'Бургас',municipality:'Царево',name:'Скалите'},
{region:'Бургас',municipality:'Царево',name:'Лафина - север 1'},
{region:'Бургас',municipality:'Царево',name:'Манастирич'},
{region:'Бургас',municipality:'Царево',name:'Варвара север'},
{region:'Бургас',municipality:'Царево',name:'Ахтопол - фара'},
{region:'Бургас',municipality:'Царево',name:'Ахтопол - север - западна зона'},
{region:'Бургас',municipality:'Царево',name:'Айроди - север'},
{region:'Бургас',municipality:'Царево',name:'Айроди - юг'},
{region:'Бургас',municipality:'Царево',name:'Липите'},
{region:'Бургас',municipality:'Царево',name:'Листи'},
{region:'Бургас',municipality:'Царево',name:'Силистар-север'},
{region:'Бургас',municipality:'Царево',name:'Резово - кастрич'},
{region:'Бургас',municipality:'Царево',name:'Резово'}
];

const natureTourismBeaches2026=[
{name:'Бяла - Карадере',municipality:'Бяла',region:'Варна'},
{name:'Иракли',municipality:'Несебър',region:'Бургас'},
{name:'Корал',municipality:'Царево',region:'Бургас'}
];

// 2026 examples where Burgas regional administration procured partial lifeguard coverage.
// Exact post coordinates are intentionally NOT invented.
const partialLifeguardCoverage2026={
  'Иракли':{jul:2,aug:2,sep:1,note:'Частично обезпечаване; през септември се закрива пост №2.'},
  'Несебър- изток':{jul:2,aug:2,sep:1,note:'Частично обезпечаване; през септември се закрива пост №1.'},
  'Поморийска коса':{jul:2,aug:2,sep:1,note:'Частично обезпечаване; през септември се закрива пост №1.'},
  'Крайморие - север 1':{jul:2,aug:2,sep:1,note:'Частично обезпечаване; през септември се закрива пост №1.'},
  'Алепу':{jul:2,aug:2,sep:1,note:'Частично обезпечаване; през септември се закрива пост №2.'},
  'Резово':{jul:1,aug:1,sep:1,note:'Частично обезпечаване през юли–септември.'}
};

// VERIFIED OFFICIAL LIFEGUARD POSTS
// Source: Областна администрация Бургас, "Схеми плажове 2020".
// Original coordinates are BGS2005 / CCS2005 (EPSG:7801); lat/lng below are WGS84 conversions.
// We keep source metadata because physical post positions can change between seasons.
const officialLifeguardPosts=[
  {beach:'Иракли',post:1,lat:42.7459772,lng:27.8900105,sourceYear:2020,sourceType:'official_scheme',verified:true},
  {beach:'Иракли',post:2,lat:42.7408757,lng:27.8913621,sourceYear:2020,sourceType:'official_scheme',verified:true},

  {beach:'Несебър - изток',post:1,lat:42.6563803,lng:27.7328875,sourceYear:2020,sourceType:'official_scheme',verified:true},

  {beach:'Поморийска коса',post:1,lat:42.5835446,lng:27.6325721,sourceYear:2020,sourceType:'official_scheme',verified:true},
  {beach:'Поморийска коса',post:2,lat:42.5808696,lng:27.6328848,sourceYear:2020,sourceType:'official_scheme',verified:true},

  {beach:'Атанасовска коса',post:1,lat:42.5276076,lng:27.4903875,sourceYear:2020,sourceType:'official_scheme',verified:true},
  {beach:'Атанасовска коса',post:2,lat:42.5196642,lng:27.4871377,sourceYear:2020,sourceType:'official_scheme',verified:true},

  {beach:'Крайморие - юг 2',post:1,lat:42.4404921,lng:27.5022586,sourceYear:2020,sourceType:'official_scheme',verified:true},
  {beach:'Крайморие - юг 2',post:2,lat:42.4389538,lng:27.5052856,sourceYear:2020,sourceType:'official_scheme',verified:true},

  {beach:'Алепу',post:1,lat:42.3650353,lng:27.7102010,sourceYear:2020,sourceType:'official_scheme',verified:true},
  {beach:'Алепу',post:2,lat:42.3560023,lng:27.7165006,sourceYear:2020,sourceType:'official_scheme',verified:true},

  {beach:'Корал',post:1,lat:42.2172663,lng:27.7897216,sourceYear:2020,sourceType:'official_scheme',verified:true},
  {beach:'Корал',post:2,lat:42.2154154,lng:27.7926317,sourceYear:2020,sourceType:'official_scheme',verified:true}
];

// For official 2026 "unguarded" status we only plot a warning when we have a trustworthy mapped anchor.
// Several have partial seasonal lifeguard provision despite their official unguarded status.
const officialUnguardedAnchors=[
  {name:'Иракли',lat:42.7434,lng:27.8907,partialCoverage:true},
  {name:'Несебър - изток',lat:42.65638,lng:27.73289,partialCoverage:true},
  {name:'Поморийска коса',lat:42.5822,lng:27.6327,partialCoverage:true},
  {name:'Атанасовска коса - част 2',lat:42.5236,lng:27.4888,partialCoverage:false},
  {name:'Крайморие - юг 2',lat:42.4397,lng:27.5038,partialCoverage:false},
  {name:'Алепу',lat:42.3605,lng:27.7134,partialCoverage:true},
  {name:'Корал',lat:42.2163,lng:27.7912,partialCoverage:false}
];


const registryAudit2026={
  mappedBeachEntries: 96,
  officialUnguardedNames: 91,
  unguardedNamesWithoutExactMappedEntry: [
    "Космос",
    "Дуранкулак - езеро",
    "Крапец-север - част",
    "Крапец-централен",
    "Крапец - юг",
    "Добруджа - север 1 и Добруджа - север 2",
    "Добруджа - юг - част",
    "Русалка (комплекс от плажове)",
    "Тауклиман",
    "Тузлата",
    "Сребристият бряг",
    "Робинзон 2",
    "Фиш - фиш - нов",
    "Чайка - централен 2",
    "Чайка - централен 1",
    "Чайка - юг",
    "Минерален басейн - юг",
    "Евксиноград 1",
    "Евксиноград 2",
    "Евксиноград 3",
    "Офицерски",
    "Галата - север",
    "Галата - изток",
    "Фичоза - север",
    "Фичоза - юг",
    "Хижа Черноморец - север",
    "Романтика",
    "Камчия - север 1, 2, 4 и 5",
    "Изгрев - Хоризонт",
    "Бяла - север",
    "Бяла - централен I",
    "Бяла - централен III",
    "Бяла - централен IV",
    "Бяла - Чайка, в т.ч. Бяла - Чайка 1",
    "Смриките",
    "Емона - юг",
    "Емона - Бунарджика",
    "Елените - изток 1 и 2",
    "Елените 1 и 2",
    "Козлука",
    "Робинзон-запад 2",
    "Несебър- изток",
    "Ахелой -север",
    "Къмпинг Ахелой - без част 3",
    "Поморийска коса",
    "Поморие Буната",
    "Къмпинг Европа",
    "Лахана 1",
    "Сарафово - север",
    "Атанасовска коса - част 2",
    "Крайморие - север 1",
    "Крайморие - север 2",
    "Крайморие - север 3",
    "Крайморие - юг 1 и 2",
    "Отманли",
    "Росенец - запад",
    "Росенец - централен",
    "Росенец - изток",
    "Вромос",
    "Алепу",
    "Аркутино лилии",
    "Ропотамо",
    "Малък оазис 1, 2, 3 и 4",
    "Малък оазис зона 1,2,4 - централен-изток",
    "Царево - север 1, 2 и 3",
    "Попски плаж - север 1, 2, 3, 4 и 5",
    "Царево - централен",
    "Царево - Василико",
    "Скалите",
    "Лафина - север 1",
    "Манастирич",
    "Варвара север",
    "Айроди - север",
    "Айроди - юг",
    "Силистар-север",
    "Резово - кастрич",
    "Резово"
  ],
  note: "Pending names are kept in the official catalogue but are not placed on Google Maps until a trustworthy coordinate is verified."
};
